[project]
name = "lysai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.43.0",
    "langgraph>=0.6.10",
    "python-dotenv>=1.1.1",
]
